### PR TITLE
Quote unquoted strings in behat.yml

### PR DESCRIPTION
**Pull request by ScopeyNZ**

### CODE REVIEW

**Review by robbieaverill — COMMENTED** [review]
Can you make this a patch change into the earliest available release branch? Then we can merge up.

**Comment by ScopeyNZ** [comment]
Done.

**Review by robbieaverill — APPROVED** [review]

**Comment by robbieaverill** [comment]
The last 1.0 branch build passed two years ago... The test failures I looked at tell me we need to pull in Sam's PHPUnit support module for PHP 7.4, and that the behat-extension module also has YML which needs to be quoted.

**Comment by ScopeyNZ** [comment]
I'm not really interested in chasing failures in well out-of-date branches. Are we happy for me to rebase on 1.3 which at least has passing builds?

**Comment by robbieaverill** [comment]
Fair enough. The CI build statuses are not relevant to the changes in this PR.

**Pull request merged**
