### PR TITLE
FIX published label used in all saved history item

### LINKED ISSUE #255: BUG: History Records are not showing the page version state correctly
The Records in History tab of a page are not showing the page version state correctly. 

- It shows 'Published' when the page is actually only **saved** but not **published**
- All version records turn to 'Saved' except for the first 'Created' record when the page is 'unpublished'

## Acceptance criteria
- [ ] The messaging on the version history page is consistent.
- [ ] The state of each version is correct.
- [ ] The scenario is covered by a behat test.

https://user-images.githubusercontent.com/81267819/193479344-fdb5e215-95be-49fe-9a5c-4b237db0ecc4.mov

The logic for showing the state seems have bug: https://github.com/silverstripe/silverstripe-versioned-admin/blob/0e407f2c790ec449df04a2a3880136b5d77bcf3a/client/src/components/HistoryViewer/HistoryViewerVersionState.js#L25

## PRs
- https://github.com/silverstripe/silverstripe-versioned/pull/402
- https://github.com/silverstripe/silverstripe-versioned-admin/pull/283

### PR DESCRIPTION
**Pull request by satrun77**
Fixes #255

### CODE REVIEW

**Comment by michalkleiner** [comment]
The test failure seems relevant, @satrun77 can you please check why it's failing and adjust as needed? Thanks.

**Comment by satrun77** [comment]
I'm going to redo the fix to show the revisions that had previously been published to say ‘Published’, instead of using `Saved` for everything.

**Comment by hirenatfos** [comment]
With this fix.
When page is in unpublished state version history states not showing correctly.

**Comment by michalkleiner** [comment]
@satrun77 keen to take a look at @hirenatfos's use case? @hirenatfos can you provide some screenshots of what you see and what you expect to see or any relevant steps to be able to replicate the situation? Thanks!

**Comment by GuySartorelli** [comment]
The issue this is intended to fix has been closed as fixed, so this PR isn't needed anymore.

**Pull request closed without merging**
