### PR TITLE
BUG Use more resilient method to manipulate URL of preview

### PR DESCRIPTION
**Pull request by maxime-rainville**
Use a more robust method for generating the URL.

# Depends on 
* https://github.com/silverstripe/webpack-config/pull/43
* https://github.com/silverstripe/silverstripe-admin/pull/999

# Parent issue
* https://github.com/silverstripe/silverstripe-versioned-admin/issues/134

### CODE REVIEW

**Comment by maxime-rainville** [comment]
Don't merge until the webpack config is merged and release otherwise we'll ship an extra dependency in this module that's included in the admin vendor bundle.

**Comment by robbieaverill** [comment]
@maxime-rainville webpack config is merged, I'll leave it to you to update this PR 👍

**Comment by maxime-rainville** [comment]
The webpack changes got merged. I just push a commit to upgrade the webpack config.

**Comment by robbieaverill** [comment]
Merge on green

**Pull request merged**
