### PR TITLE
FIX Use the new HtmlDiff class

### PR DESCRIPTION
**Pull request by GuySartorelli**
Uses the new class name introduced in https://github.com/silverstripe/silverstripe-framework/pull/10641

## Parent issue
- https://github.com/silverstripe/silverstripe-framework/issues/10640

### CODE REVIEW

**Comment by GuySartorelli** [comment]
Unit tests will fail until the framework PR is merged in

**Review by sabina-talipova — DISMISSED** [review]

**Comment by sabina-talipova** [comment]
Could you resolve conflict, please

**Comment by GuySartorelli** [comment]
Rebased and conflicts resolved. It's possible that there were new tests added which will need to be updated so if it fails after merging framework, kick it back to me and I'll fix it.

**Review by sabina-talipova — APPROVED** [review]
Test locally after rebase and resolving conflict. Tests passed. Approve. 
It will be merged in after framework PR.

**Comment by GuySartorelli** [comment]
Looks like I incorrectly resolved the merge conflict before - the tests were failing locally for me. Fixed now.

**Comment by GuySartorelli** [comment]
Added null coallescing operators to catch the error referenced in https://github.com/silverstripe/silverstripe-framework/pull/10641#issuecomment-1421819706

**Comment by sabina-talipova** [comment]
Failed JS tests are unrelated to these changes.

**Pull request merged**
