### PR TITLE
Revert translation updates

### PR DESCRIPTION
**Pull request by emteknetnz**
Reverts bits of
https://github.com/silverstripe/silverstripe-versioned-admin/commit/ae029a698e013aa93642478815a8933b6f063028
https://github.com/silverstripe/silverstripe-versioned-admin/commit/6ae51941c8b2340cfeb6d0101990fa45c552aed0#diff-e1b902603902928d998b45fdd61f2b72b0ce12e723b160601cce88d2d2077406L28

The correct value for TAB_OTHERS is 'Other'
https://github.com/silverstripe/silverstripe-versioned-admin/commit/afc460c8e7a225197bc19a82ca7591853089b299#diff-0df2677d84007a9e9dbf1c06cbc8ee7cc2ceb663efb442203e5206de2efcdf32R10

### CODE REVIEW

**Comment by Cheddam** [comment]
I'm a bit worried about the `MENUTITLE` entries being left as empty strings - this will result in the tab name being blank. A fallback to English would surely be a better outcome there.

I've [raised an issue](https://github.com/silverstripe/silverstripe-framework/issues/9791) to handle empty translation values differently, but in the meantime perhaps we should drop these empty keys out.

**Comment by emteknetnz** [comment]
@Cheddam Where are the empty strings?  This PR reverts doesn't "add" any empty strings?

**Comment by Cheddam** [comment]
They're [here](https://github.com/silverstripe/silverstripe-versioned-admin/commit/ae029a698e013aa93642478815a8933b6f063028#diff-4ccd4fb8579bf53c4662ed7448674f50df9c095155682a3d69cd90351e3cd072R13), in one of the dodgy translation updates. You can see that those empty keys are still in place in the surrounding content of the diff for this PR.

**Comment by emteknetnz** [comment]
OK have removed the empty strings

**Review by Cheddam — APPROVED** [review]

**Pull request merged**
